ip = "127.0.0.1"
port = 8000
db_path = "/etc/rotproxy/users.json"
html_path = "/etc/rotproxy/index.html"
webroot_route = "rotproxy"
login_route = ""
auth_endpoint = "auth"
login_endpoint = "login"
login_redirect = ""
logout_endpoint = "logout"
logout_redirect = ""
trusted_proxies = ["127.0.0.1"]
magic_str = ""
magic_bytes = 32
magic_str_duration = "1h"
magic_str_char_range = "0:10"
rate_limit_max_user_attempts = 3
rate_limit_user_window = 1800
rate_limit_max_ip_attempts = 4
rate_limit_ip_window = 1800
rate_limit_bg_prune_job = 120
content_policy = "default-src 'self'; style-src 'self'; form-action 'self'; script-src 'self' 'sha256-xKOX32ceTgoNvySGOBePspULR2AmjzrMejHixwmcSgo='"
cookie_key = "cc044309e66abc519483206ff47d96401c71d9ad66b4cea5fe41a92a98935512"
cookie_name = "rotproxy_session"
cookie_path = "/"
cookie_domain = ""
cookie_secure = true
session_ttl = 3600
session_abs_ttl = 28800
hash_mem_cost = 64
hash_time_cost = 3
hash_parallel_cost = 4

